export const chats = [
  {
    id: 1,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod',
        type: 'out',
        time: '17:31',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet,',
        type: 'out',
        time: '11:42',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectet',
        type: 'out',
        time: '12:25',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, s',
        type: 'in',
        time: '12:25',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labo',
        type: 'in',
        time: '09:19',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing e',
        type: 'out',
        time: '04:22',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu',
        type: 'out',
        time: '14:14',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo',
        type: 'in',
        time: '08:27',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit a',
        type: 'in',
        time: '16:22',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, co',
        type: 'out',
        time: '02:34',
        isRead: 0,
      },
    ],
  },
  {
    id: 2,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
        type: 'in',
        time: '22:59',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labo',
        type: 'out',
        time: '14:07',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetu',
        type: 'out',
        time: '15:30',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur',
        type: 'out',
        time: '14:38',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit ame',
        type: 'in',
        time: '01:38',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inc',
        type: 'out',
        time: '08:05',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempo',
        type: 'in',
        time: '00:28',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem',
        type: 'out',
        time: '02:31',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmo',
        type: 'in',
        time: '04:42',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu',
        type: 'in',
        time: '16:10',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do',
        type: 'in',
        time: '08:55',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ',
        type: 'out',
        time: '15:06',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem',
        type: 'in',
        time: '05:01',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ',
        type: 'in',
        time: '11:20',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, cons',
        type: 'out',
        time: '09:55',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem i',
        type: 'out',
        time: '21:44',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do',
        type: 'out',
        time: '05:52',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolo',
        type: 'out',
        time: '20:10',
        isRead: false,
      },
    ],
  },
  {
    id: 3,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt u',
        type: 'out',
        time: '03:26',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing el',
        type: 'in',
        time: '00:04',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor',
        type: 'out',
        time: '08:22',
        isRead: true,
      },
    ],
  },
  {
    id: 4,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit ame',
        type: 'in',
        time: '20:16',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm',
        type: 'in',
        time: '03:31',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, se',
        type: 'out',
        time: '05:30',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, se',
        type: 'in',
        time: '01:56',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur ',
        type: 'out',
        time: '13:12',
        isRead: true,
      },
    ],
  },
  {
    id: 5,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labor',
        type: 'in',
        time: '14:16',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, c',
        type: 'out',
        time: '01:48',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi',
        type: 'in',
        time: '15:39',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ',
        type: 'in',
        time: '11:10',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore',
        type: 'out',
        time: '10:44',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit am',
        type: 'in',
        time: '00:31',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit a',
        type: 'in',
        time: '22:43',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod t',
        type: 'in',
        time: '23:14',
        isRead: false,
      },
    ],
  },
  {
    id: 6,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut l',
        type: 'in',
        time: '20:10',
        isRead: false,
      },
    ],
  },
  {
    id: 7,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ',
        type: 'in',
        time: '05:50',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi',
        type: 'out',
        time: '04:09',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem i',
        type: 'out',
        time: '03:00',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ip',
        type: 'in',
        time: '02:22',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid',
        type: 'in',
        time: '07:31',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur a',
        type: 'out',
        time: '07:57',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum ',
        type: 'in',
        time: '11:09',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet,',
        type: 'in',
        time: '21:59',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in',
        type: 'in',
        time: '17:42',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit',
        type: 'in',
        time: '22:56',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
        type: 'in',
        time: '12:37',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore ',
        type: 'out',
        time: '22:33',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu',
        type: 'out',
        time: '21:37',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipi',
        type: 'in',
        time: '20:10',
        isRead: false,
      },
    ],
  },
  {
    id: 8,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore',
        type: 'out',
        time: '04:43',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ',
        type: 'out',
        time: '23:02',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsu',
        type: 'in',
        time: '19:31',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inc',
        type: 'in',
        time: '06:39',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, ',
        type: 'in',
        time: '13:38',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor si',
        type: 'in',
        time: '01:38',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipisc',
        type: 'in',
        time: '22:40',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit ',
        type: 'in',
        time: '15:25',
        isRead: false,
      },
    ],
  },
  {
    id: 9,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet',
        type: 'in',
        time: '23:57',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor',
        type: 'in',
        time: '22:02',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu',
        type: 'out',
        time: '13:32',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adip',
        type: 'in',
        time: '04:41',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dol',
        type: 'in',
        time: '08:05',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut lab',
        type: 'out',
        time: '04:05',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur ad',
        type: 'in',
        time: '16:23',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi',
        type: 'out',
        time: '13:25',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor',
        type: 'out',
        time: '21:39',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed d',
        type: 'out',
        time: '20:49',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dol',
        type: 'in',
        time: '09:38',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscin',
        type: 'out',
        time: '01:15',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit ame',
        type: 'out',
        time: '14:06',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipis',
        type: 'in',
        time: '15:52',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, conse',
        type: 'out',
        time: '07:35',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adi',
        type: 'out',
        time: '22:17',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit ame',
        type: 'out',
        time: '02:05',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur ad',
        type: 'out',
        time: '20:10',
        isRead: false,
      },
    ],
  },
  {
    id: 10,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e',
        type: 'out',
        time: '10:10',
        isRead: false,
      },
    ],
  },
  {
    id: 11,
    messages: [
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
        type: 'out',
        time: '09:03',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inc',
        type: 'out',
        time: '15:29',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu',
        type: 'in',
        time: '17:02',
        isRead: true,
      },
      {
        id: Math.floor(Math.random() * Math.floor(999999)),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor i',
        type: 'out',
        time: '22:10',
        isRead: true,
      },
    ],
  },
];
